### ISSUE TITLE
Crash-report!

### ISSUE THREAD

**Issue by seriousfreezing** [cybercat5555/Miskatonic-Mysteries-Fabric#105]
https://pastebin.com/iy64B85z

**Comment by Poopooracoocoo** [comment]
Offending line is https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/blob/71a86bd5fbff4185c4f3e941ebf4ab998cd528f2/src/main/java/com/miskatonicmysteries/mixin/entity/LivingEntityMixin.java#L43

As a workaround you can downgrade Fabric Loader to 0.14.25 on your server.

For a similar issue, see https://github.com/MoriyaShiine/extra-origins/issues/216

May be fixed by https://github.com/cybercat5555/Miskatonic-Mysteries-Fabric/pull/106


Crash report for searchability:
<details><summary>Details</summary>

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/8/24, 4:16 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: mm_squishTicks
    at net.minecraft.class_1309.<init>(class_1309.java:242)
    at net.minecraft.class_1657.<init>(class_1657.java:200)
    at net.minecraft.class_3222.<init>(class_3222.java:246)
    at net.minecraft.class_3324.method_14613(class_3324.java:454)
    at net.minecraft.class_3248.method_14384(class_3248.java:112)
    at net.minecraft.class_3248.redirect$bkb000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563)
    at net.minecraft.class_3248.method_18785(class_3248.java:67)
    at net.minecraft.class_2535.method_10754(class_2535.java:243)
    at net.minecraft.class_3242.method_14357(class_3242.java:183)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
    at net.minecraft.class_3176.method_3813(class_3176.java:322)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
    at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.18.2
    Minecraft Version ID: 1.18.2
    Operating System: Linux (amd64) version 5.15.0-58-generic
    Java Version: 17.0.8, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
    Memory: 1134540816 bytes (1081 MiB) / 3233808384 bytes (3084 MiB) up to 8589934592 bytes (8192 MiB)
    CPUs: 24
    Processor Vendor: GenuineIntel
    Processor Name: Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz
    Identifier: Intel64 Family 6 Model 63 Stepping 2
    Microarchitecture: Haswell (Server)
    Frequency (GHz): 3.40
    Number of physical packages: 2
    Number of physical CPUs: 12
    Number of logical CPUs: 24
    Graphics card #0 name: unknown
    Graphics card #0 vendor: unknown
    Graphics card #0 VRAM (MB): 0.00
    Graphics card #0 deviceId: unknown
    Graphics card #0 versionInfo: unknown
    Virtual memory max (MB): 174687.78
    Virtual memory used (MB): 198107.53
    Swap memory total (MB): 45773.99
    Swap memory used (MB): 8970.74
    JVM Flags: 2 total; -Xmx8192M -Xms512M
    Fabric Mods: 
        ad_astra: Ad Astra 1.0.9
            team_reborn_energy: Energy 2.2.0
        advanced_reborn: Advanced Reborn 1.2.6
        ae2: Applied Energistics 2 11.7.6
        ae2wtlib: AE2WTLib 11.6.3
        arcanus: Arcanus 1.29.2
        architectury: Architectury 4.12.94
        attributefix: AttributeFix 14.0.2
        autoconfig1u: Auto Config v1 Updated 3.4.0
        bookshelf: Bookshelf 13.3.56
        botania: Botania 1.18.2-435-FABRIC
            fiber: fiber 0.23.0-2
            step-height-entity-attribute: Step Height Entity Attribute 1.0.0
        charm: Charm 4.4.4
            com_moandjiezana_toml_toml4j: toml4j 0.7.2
        chipped: Chipped 2.0.1
        create: Create 0.5.1-c-build.1159+mc1.18.2
            com_google_code_findbugs_jsr305: jsr305 3.0.2
            forgeconfigapiport: Forge Config API Port 3.2.4
            milk: Milk Lib 0.3.2
                dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
            porting_lib: Porting Lib 1.2.1095-beta+1.18.2
                serialization_hooks: Serialization Hooks 0.3.23
            registrate-fabric: Registrate for Fabric MC1.18.2-1.1.11
        createaddition: Create Crafts & Additions 20230704a
        dankstorage: Dank Storage 1.18.2-3.9
        debugify: Debugify 1.11.0
        expandedstorage: Expanded Storage 8.3.3
        explorerscompass: Explorer's Compass 1.18.2-2.2.0-fabric
        extended_drawers: Extended Drawers 1.3.7+mc.1.18.2
            graphlib: Graph Lib 0.2.4+1.18.2
            mconfig: Mconfig 1.2.0
                de_poiu_apron_apron: apron 2.1.1
        fabric-api: Fabric API 0.77.0+1.18.2
            fabric-api-base: Fabric API Base 0.4.5+64b7c69360
            fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
            fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
            fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
            fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
            fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
            fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
            fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
            fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
            fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
            fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
            fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
            fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
            fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
            fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
            fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
            fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
            fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
            fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
            fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
            fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
            fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
            fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
            fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
            fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
            fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
            fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
            fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
            fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
            fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
            fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
            fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
            fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
            fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
        fabric-furnaces: Fabric Furnaces 2.1.1-1.18.2
            omega-config: OmegaConfig 1.2.3-1.18.1
        fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
            org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
            org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
            org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
            org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
            org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
            org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
            org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
            org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
            org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
            org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
            org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
        fabricloader: Fabric Loader 0.15.7
            mixinextras: MixinExtras 0.3.5
        ferritecore: FerriteCore 4.2.1
        fwaystones: Fabric Waystones 3.0.0+mc1.18.2
        gardenarsenal: Garden Arsenal 0.4.2
        geckolib3: Geckolib 3.0.80
            com_eliotlash_mclib_mclib: mclib 20
        gobber2: Gobber2 2.5.81
            pugh_lib: Pugh Lib 1.3.2
            pugh_tools: Pugh Tools 1.2.7
        haema: Haema 1.10.1+1.18.2
            patchouli: Patchouli 1.18.2-67-FABRIC
            pehkui: Pehkui 3.2.2+1.14.4-1.19
                kanos_config: Kanos Config 0.2.0+1.14.4-1.19
        hwg: Happiness is a Warm Gun 1.1.12
        iron-jetpacks: Iron Jetpacks 0.4.3
        jade: Jade 5.100.0
        java: Java HotSpot(TM) 64-Bit Server VM 17
        kibe: Kibe 1.9.11-BETA+1.18
        krypton: Krypton 0.1.9
            com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
        lazydfu: LazyDFU 0.1.2
        led: Light Emitting Diode 1.2.4
            jmxl: JMXL 1.0
        lithium: Lithium 0.10.3
        lootr: Lootr 0.3.28.65
        mcpitanlib: MCPitanLib 2.1.9-1.18.2-fabric
            cloth-config: Cloth Config v6 6.5.116
                cloth-basic-math: cloth-basic-math 0.6.1
            org_yaml_snakeyaml: snakeyaml 2.0
        minecraft: Minecraft 1.18.2
        miskatonicmysteries: Miskatonic Mysteries 0.1.3
            bannerpp: Banner++ 2.0.6-teb.1+mc.1.18.2
            cloth-client-events-v0: Cloth Client Events v0 3.1.61
            midnightlib: MidnightLib 0.4.0
        modern_industrialization: Modern Industrialization 1.2.3
            magna: Magna 1.7.0-1.18-pre1
            playerabilitylib: Pal 1.5.0
        modernfix: ModernFix 5.14.0+mc1.18.2
        mr_veinminer: Veinminer 1.1.0
        mysticalcrops: Mystical Nature 1.8.5-1.18.2
        naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
        nerb: Not Enough Recipe Book 0.3
        opchanter: OPChanter 1.18.2-1.0.0-fabric
        origins: Origins 1.4.1
            apoli: Apoli 2.3.3
                calio: Calio 1.5.1
        origins-plus-plus: Origins++ 2.2
        pfm: Paladin's Furniture 1.2.1
        powah: Powah! 3.0.8
        reinfchest: Reinforced Chests 2.2.0+1.18
            reinfcore: Reinforced Core 3.0.3+1.18
        roughlyenoughitems: Roughly Enough Items 8.3.681
            error_notifier: Error Notifier 1.0.9
        securityforfabric: Security For Fabric 1.2.0-1.18.2
        servercore: ServerCore 1.2.9-1.18.2
            com_electronwill_night-config_core: core 3.6.5
            com_electronwill_night-config_toml: toml 3.6.5
            placeholder-api: Placeholder API 1.1.3+1.17.1
        shrink_rays: ShrinkRays 1.0
        simplevillagers: Simple Villagers 1.2.2
            config2brigadier: Config to Brigadier 1.1.1
            fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
            polymer: Polymer (Core) 0.2.0-beta.28+1.18.2
                packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
                polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.28+1.18.2
            server_translations_api: Server Translations API 1.4.10+1.18.2
            sgui: sgui 1.0.0+1.18.1
        simplevoidworld: Simple Void World 4.0.0
        smoothboot: Smooth Boot 1.18.2-1.7.0
        starlight: Starlight 1.0.2+fabric.89b8d9f
        stylish_occult: Stylish Occult 0.12.2
            interference: Interference API 1.5.0
            libgui: LibGui 5.4.2+1.18.2
                jankson: Jankson 4.0.0+j1.2.0
                    blue_endless_jankson: jankson 1.2.1
                libninepatch: LibNinePatch 1.1.0
            loot_boxes: Loot Boxes 0.1.5
        techreborn: Tech Reborn 5.2.1
            reborncore: Reborn Core 5.2.1
        the_aether: Paradise Lost 1.6.9+1.18.2
            crowdin-translate: CrowdinTranslate 1.4+1.18.2
            customportalapi: Custom Portal Api 0.0.1-beta50-1.18
            gud_recipe_confidence: Recipe Confidence 1.0.2
            incubus_core: Incubus Core 1.6.6+1.18.2
            moretags: More Tags 3.0.4
            trinkets: Trinkets 3.3.0
        tiered: Tiered 1.1.1
            additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
            autotag: AutoTag 1.1.0
        travelersbackpack: Traveler's Backpack 1.18.2-7.1.36
            reach-entity-attributes: Reach Entity Attributes 2.2.0
        twilightforest: The Twilight Forest 4.1.313
            cardinal-components-base: Cardinal Components API (base) 4.1.4
            cardinal-components-entity: Cardinal Components API (entities) 4.1.4
            forge_tags: Forge Tags 2.1
            javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
            mm: Manningham Mills 2.3
        vmp: Very Many Players 0.2.0+beta.3.126
        wands: Building Wands 2.6.9-release
        wirelessnetworks: Wireless Networks 1.5.1
        zenith: Zenith 0.3.0
            fake-player-api: Fake Player API 0.3.0
    Server Running: true
    Player Count: 0 / 15; []
    Data Packs: vanilla, Fabric Mods, pfm-data-resources
    World Generation: Experimental
    Is Modded: Definitely; Server brand changed to 'fabric'
    Type: Dedicated Server (map_server.txt)
``` 

</details>

**Comment by anticode-403** [comment]
Seconding this issue. I can't downgrade to 0.14.25 for other reasons. Do you intend to fix this for previous versions of your mod, like mc-1.19.2?

**Comment by Poopooracoocoo** [comment]
@anticode-403 Most mods don't really require Fabric Loader 0.15.0 and above. That means you can create a [dependency override](https://fabricmc.net/wiki/tutorial:dependency_overrides) to ignore those dependencies. 

Or you could download https://github.com/BehindTheScenery/Miskatonic-Mysteries-Fabric/releases

If you're on Aternos where you can't get any mod and where you can't change your Fabric Loader version, you're out of luck until the author makes a new release.

Edit: the commenter I replied to has deleted their comment.

**Comment by seriousfreezing** [comment]
Relax, I haven't had this bug for a while and that's why I haven't replied. But I'll use the fabric loader dependencies anyway, thanks!
