### ISSUE TITLE
The server i run when I eat or use a tranquiller it kicks me (log underneath)

### ISSUE THREAD

**Issue by blarg2-5** [cybercat5555/Miskatonic-Mysteries-Fabric#11]
[13:35:16] [Server thread/WARN]: Failed to handle packet for /192.168.0.1:58045
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1309.method_26082(Lnet/minecraft/class_1293;)V
        at com.miskatonicmysteries.common.item.consumable.BlotterItem.method_7861(BlotterItem.java:31) ~[miskatonicmysteries-0.0.3.jar:?]
        at net.minecraft.class_1799.method_7910(class_1799.java:243) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_6040(class_1309.java:2941) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_6040(class_3222.java:1140) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_6076(class_1309.java:2821) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2210) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
        ... 9 more
[13:35:16] [Server thread/INFO]: Blarg2_5 lost connection: Internal server error
[13:35:16] [Server thread/INFO]: Blarg2_5 left the game
[13:35:16] [Server thread/INFO]: Disconnecting client Blarg2_5

**Comment by Aelpecyem** [comment]
This is a duplicate issue that has been fixed indev, you'll need to wait for another release
